[package]
name = "quote-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
hex = "0.4.3"
sha3 = "0.10.6"
tokio = { version = "1.25.0", features = ["full"] }
